<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PemetaanSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');
        $data = [
            ['pola_uraian' => 'Angsuran Pinjaman%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 5, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Cadangan Aktiva Produktif (CAP)%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 6, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Denda%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 7, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Fee (Anggota Keluar)%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 8, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Fee Persentase (Profisi) 1\%%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 9, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Jasa Piutang%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 11, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyisihan Dana Rapat Tahunan (RAT)%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 100, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyisihan Dana Pemilihan Pengurus%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 13, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pinjaman dari Bank Pembangunan Daerah (BPD)%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 14, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Risiko (Re) 0,5\%%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 15, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Jasa Simpanan Non-Saham%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 17, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Simpanan Non-Saham%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 16, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Simpanan Pokok (SP)%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 18, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Simpanan Sukarela (SS)%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 19, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Simpanan Wajib (SW)%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 20, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Simpanan Wajib Penyertaan (SWP)%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 21, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana dari Bank%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 22, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan Dana Kesejahteraan%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 23, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan Tunjangan Pesangon Karyawan%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 24, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Uang Pangkal%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 25, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Administrasi/Pajak Bank%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 92, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Bensin%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 75, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya BPJS%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 97, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Bunga Hutang Bank%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 91, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Gaji Karyawan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 62, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya IPTW (Insentif Pekerja Tidak Tetap Wajib)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 67, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Koordinator%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 68, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Lembur%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 76, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Minum%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 69, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Non-Saham%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 77, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Organisasi%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 61, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Pajak Listrik%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 111, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Pajak Wi-Fi%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 115, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Pemilihan Pengawas/Pengurus%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 96, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Tunjangan Anak%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 64, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Tunjangan Istri%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 63, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Administrasi%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 60, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Cadangan Aktiva Produktif (CAP)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 6, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyisihan Dana Kesejahteraan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 101, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyisihan Tunjangan Pensiun Karyawan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 98, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pinjaman Anggota%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 35, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Karyawan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 47, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Kesejahteraan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 58, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Pengurus%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 46, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Sosial%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 49, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Jasa Simpanan Non-Saham%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 44, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Sisa Hasil Usaha (SHU)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 55, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Simpanan Non-Saham%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 43, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Simpanan Pokok (SP)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 39, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Simpanan Sukarela (SS)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 42, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Simpanan Wajib (SW)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 40, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Simpanan Wajib Penyertaan (SWP)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 41, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Titipan Dana RAT%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 51, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Akumulasi Penyusutan Inventaris Komputer%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Akumulasi Penyusutan Inventaris Mebel%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 2, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Akumulasi Penyusutan Inventaris Kendaraan%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 4, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Akumulasi Penyusutan Inventaris Gedung%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 3, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pendapatan Jasa Pinjaman%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 10, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Dana Cadangan RAT%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 12, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan Dana RAT%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 26, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan Dana Pendampingan%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 27, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan Penyisihan Pajak SHU%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 28, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Modal Tetap%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 29, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pendapatan Lain-lain%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 118, 'id_akun_kredit' => 30, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pendapatan Hibah%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 31, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pendapatan Jasa Simpanan Bank%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 32, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pendapatan Jasa Deposito%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 33, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan Pajak Jasa Non Saham%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 118, 'id_akun_kredit' => 34, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Simpanan di Bank%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 36, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Simpanan Deposito%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 37, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Angsuran pinjaman ke BPD%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 38, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik titip (SP, SW, SWP, SS)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 45, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Pendidikan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 48, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana PDK%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 50, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Risiko%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 52, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Pemupukan Modal Tetap%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 53, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana CAP%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 54, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik THT%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 56, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Titipan Pajak%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 57, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Pendampingan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 59, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'THR (karyawan)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 65, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya insentif pengurus & pengawas%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 66, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya penjaga/kebersihan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 70, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'THR Penjaga%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 71, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Harkop/Besar Nasional%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 72, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Transportasi%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 73, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Transportasi rapat%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 74, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Perawatan Inventaris%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 78, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya kalender/promosi%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 79, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya pendidikan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 80, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Perawatan gedung%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 81, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Dana Sosial%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 82, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Bonus pencapaian target%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 83, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya kesejahteraan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 84, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya audit pengawas%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 85, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya supervisi pengurus%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 86, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Insentif koordinator%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 87, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya syawalan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 88, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Bingkisan lebaran%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 89, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Seragam%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 90, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pesangon purna karyawan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 93, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Denda pajak%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 95, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'CAP (Cadangan Aktiva Produktif)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 99, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyertaan Modal Tetap%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 102, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Proyektor%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 103, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyisihan pendampingan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 104, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyusutan tertagih%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 106, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyusutan Inventaris Mebel%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 107, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyusutan Inventaris Gedung%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 108, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyusutan Inventaris Kendaraan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 109, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyusutan Inventaris Komputer%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 110, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pajak PPh%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 112, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pajak PBB%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 113, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pajak SHU%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 114, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pajak jasa simpanan bank%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 116, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pajak kendaraan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 117, 'id_akun_kredit' => 118, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Dana Cadangan RAT%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 118, 'id_akun_kredit' => 12, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
        ];
        // Insert data ke database
        $this->db->table('pemetaan_akun')->insertBatch($data);
    }
}

