<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PemetaanSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');
        $data = [
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Akumulasi Penyusutan Investasi Komputer', 'id_akun_debit' => 1, 'id_akun_kredit' => 21, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Akumulasi Penyusutan Mebel', 'id_akun_debit' => 1, 'id_akun_kredit' => 12, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Akumulasi Penyusutan Gedung', 'id_akun_debit' => 1, 'id_akun_kredit' => 15, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Akumulasi Penyusutan Kendaraan', 'id_akun_debit' => 1, 'id_akun_kredit' => 23, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Angsuran Pinjaman', 'id_akun_debit' => 1, 'id_akun_kredit' => 4, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Cadangan Aktiva Produktif', 'id_akun_debit' => 1, 'id_akun_kredit' => 24, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Pendapatan Denda', 'id_akun_debit' => 1, 'id_akun_kredit' => 73, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Fee Anggota Keluar', 'id_akun_debit' => 1, 'id_akun_kredit' => 74, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Pendapatan Profisi 1%', 'id_akun_debit' => 1, 'id_akun_kredit' => 75, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Pendapatan Jasa Pinjaman', 'id_akun_debit' => 1, 'id_akun_kredit' => 76, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Dana Cadangan RAT', 'id_akun_debit' => 1, 'id_akun_kredit' => 25, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Dana Cadangan Pemilihan Pengurus', 'id_akun_debit' => 1, 'id_akun_kredit' => 26, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Pinjaman dari BPD', 'id_akun_debit' => 1, 'id_akun_kredit' => 27, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Re (Risiko) 0.5%', 'id_akun_debit' => 1, 'id_akun_kredit' => 28, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Pendapatan Jasa Simpanan Non Saham', 'id_akun_debit' => 1, 'id_akun_kredit' => 77, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Simpanan Non Saham', 'id_akun_debit' => 1, 'id_akun_kredit' => 59, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Simpanan Pokok', 'id_akun_debit' => 1, 'id_akun_kredit' => 69, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Simpanan Sukarela', 'id_akun_debit' => 1, 'id_akun_kredit' => 61, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Simpanan Wajib', 'id_akun_debit' => 1, 'id_akun_kredit' => 70, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Simpanan Wajib Penyertaan', 'id_akun_debit' => 1, 'id_akun_kredit' => 71, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Tarik dari Bank', 'id_akun_debit' => 1, 'id_akun_kredit' => 2, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Titipan Dana Kesejahteraan', 'id_akun_debit' => 1, 'id_akun_kredit' => 29, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Titipan Tunjangan Pesangon', 'id_akun_debit' => 1, 'id_akun_kredit' => 30, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Uang Pangkal', 'id_akun_debit' => 1, 'id_akun_kredit' => 31, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Titipan Dana RAT', 'id_akun_debit' => 1, 'id_akun_kredit' => 32, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Titipan Dana Pendampingan', 'id_akun_debit' => 1, 'id_akun_kredit' => 33, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Titipan Penyisihan Pajak SHU', 'id_akun_debit' => 1, 'id_akun_kredit' => 34, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Modal Tetap', 'id_akun_debit' => 1, 'id_akun_kredit' => 62, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Pendapatan Lain-lain', 'id_akun_debit' => 1, 'id_akun_kredit' => 78, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Pendapatan Hibah', 'id_akun_debit' => 1, 'id_akun_kredit' => 79, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Pendapatan Jasa Simpanan Bank', 'id_akun_debit' => 1, 'id_akun_kredit' => 80, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Pendapatan Jasa Deposito', 'id_akun_debit' => 1, 'id_akun_kredit' => 81, 'created_at' => $now],
            ['kategori_jurnal' => 'DUM', 'uraian_jurnal' => 'Titipan Pajak Jasa Non Saham', 'id_akun_debit' => 1, 'id_akun_kredit' => 35, 'created_at' => $now],

            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Peminjaman anggota', 'akun_debit' => 4, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Simpanan di Bank', 'akun_debit' => 2, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Simpanan Deposito', 'akun_debit' => 3, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Angsuran pinjaman ke BPD', 'akun_debit' => 27, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik SP', 'akun_debit' => 69, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik SW', 'akun_debit' => 70, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik SWP', 'akun_debit' => 71, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik SS', 'akun_debit' => 61, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik simp non saham', 'akun_debit' => 59, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik jasa simp non saham', 'akun_debit' => 60, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik titip (SP, SW, SWP, SS)', 'akun_debit' => 37, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik Dana Pengurus', 'akun_debit' => 38, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik Dana Karyawan', 'akun_debit' => 39, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik Dana Pendidikan', 'akun_debit' => 40, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik Dana Sosial', 'akun_debit' => 41, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik Dana PDK', 'akun_debit' => 42, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik Titipan Dana RAT', 'akun_debit' => 32, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik Dana Risiko', 'akun_debit' => 44, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik Dana Pemupukan Modal Tetap', 'akun_debit' => 48, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik Dana CAP', 'akun_debit' => 49, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik SHU', 'akun_debit' => 67, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik THT', 'akun_debit' => 68, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik Titipan Pajak', 'akun_debit' => 45, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik Dana Kesejahteraan', 'akun_debit' => 46, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Tarik Dana Pendampingan', 'akun_debit' => 47, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya Administrasi', 'akun_debit' => 83, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya Organisasi', 'akun_debit' => 84, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya Gaji Karyawan', 'akun_debit' => 85, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya Tunjangan Istri', 'akun_debit' => 86, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya Tunjangan Anak', 'akun_debit' => 87, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'THR (karyawan)', 'akun_debit' => 88, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya insentif pengurus & pengawas', 'akun_debit' => 89, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya Koordinator', 'akun_debit' => 90, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya Minum', 'akun_debit' => 91, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya penjaga/kebersihan', 'akun_debit' => 92, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'THR Penjaga', 'akun_debit' => 93, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya Harkop/Besar Nasional', 'akun_debit' => 94, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya Transportasi', 'akun_debit' => 95, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya Transportasi rapat', 'akun_debit' => 96, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya Bensin', 'akun_debit' => 97, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya Lembur', 'akun_debit' => 98, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya Non Saham', 'akun_debit' => 99, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya Perawatan Inventaris', 'akun_debit' => 100, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya kalender/promosi', 'akun_debit' => 101, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya pendidikan', 'akun_debit' => 102, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Perawatan gedung', 'akun_debit' => 103, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya Dana Sosial', 'akun_debit' => 104, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Bonus pencapaian target', 'akun_debit' => 105, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya kesejahteraan', 'akun_debit' => 106, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya audit pengawas', 'akun_debit' => 107, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya supervisi pengurus', 'akun_debit' => 108, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Insentif koordinator', 'akun_debit' => 109, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Biaya syawalan', 'akun_debit' => 110, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Bingkisan lebaran', 'akun_debit' => 111, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Seragam', 'akun_debit' => 112, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Bunga utang bank', 'akun_debit' => 113, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Adm/pajak bank', 'akun_debit' => 114, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Pesangon purna karyawan', 'akun_debit' => 115, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Modal Tetap', 'akun_debit' => 62, 'akun_kredit' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Denda pajak', 'kode_akun' => 116, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Pemilihan pengawas/pengurus', 'kode_akun' => 117, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'BPJS', 'kode_akun' => 118, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Penyisihan pesangon karyawan', 'kode_akun' => 119, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'CAP (Cadangan Aktiva Produktif)', 'kode_akun' => 24, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Penyisihan dana RAT', 'kode_akun' => 25, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Penyisihan Dana Kesejahteraan', 'kode_akun' => 46, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Penyertaan Modal Tetap', 'kode_akun' => 64, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Inventaris Mebel', 'kode_akun' => 11, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Proyektor', 'kode_akun' => 121, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Inventaris Komputer', 'kode_akun' => 20, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Inventaris Gedung', 'kode_akun' => 14, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Penyisihan pendampingan', 'kode_akun' => 47, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Penyisihan tunjangan pensiun', 'kode_akun' => 66, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Penyusutan tertagih', 'kode_akun' => 124, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Penyusutan mebeler', 'kode_akun' => 125, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Penyusutan bangunan', 'kode_akun' => 126, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Penyusutan motor', 'kode_akun' => 127, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Penyusutan komputer', 'kode_akun' => 128, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Pajak listrik', 'kode_akun' => 129, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Pajak PPh', 'kode_akun' => 130, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Pajak PBB', 'kode_akun' => 131, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Pajak SHU', 'kode_akun' => 132, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Pajak Wifi', 'kode_akun' => 133, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Pajak jasa simpanan bank', 'kode_akun' => 134, 'is_active' => 1, 'created_at' => $now],
            ['kategori_jurnal' => 'DUK', 'uraian_jurnal' => 'Pajak kendaraan', 'kode_akun' => 135, 'is_active' => 1, 'created_at' => $now],

        ];
        // Insert data ke database
        $this->db->table('pemetaan_akun')->insertBatch($data);
    }
}

